"""Stable feature definitions for the built-in acoustic pack (Tasks 5--7).

Each definition carries the exact key, pack, level, unit, prerequisites,
population applicability, formula version, and reference required by the
catalog contract. Formula details are documented on the extracting functions
in :mod:`speech_features.features.acoustic.quality`,
:mod:`speech_features.features.acoustic.timing`,
:mod:`speech_features.features.acoustic.phonation`,
:mod:`speech_features.features.acoustic.resonance`,
:mod:`speech_features.features.acoustic.spectrum`, and
:mod:`speech_features.features.acoustic.rhythm`.
"""

from __future__ import annotations

from ...catalog import FeatureDefinition, register_feature

QUALITY_KEYS = (
    "audio_duration_s",
    "audio_dc_offset",
    "audio_clipping_ratio",
    "audio_rms_dbfs",
)

TIMING_KEYS = (
    "time_speech_s",
    "time_speech_ratio",
    "time_voiced_segment_mean_s",
    "time_voiced_segment_sd_s",
    "time_pause_count",
    "time_pause_rate_per_min",
    "time_pause_mean_s",
    "time_pause_sd_s",
    "time_pause_max_s",
    "time_long_pause_count",
    "time_response_latency_s",
    "time_overlap_s",
    "time_words_per_min",
    "time_syllables_per_min",
    "time_articulation_rate_syllables_per_s",
    "time_pause_total_s",
    "time_pause_median_s",
    "time_pause_iqr_s",
    "time_pause_cv",
    "time_pause_proportion",
    "time_speech_segment_count",
    "time_speech_segment_rate_per_min",
    "time_speech_segment_median_s",
    "time_speech_segment_iqr_s",
    "time_speech_segment_cv",
    "time_speech_segment_max_s",
    "time_between_utterance_pause_proportion",
    "time_max_local_speech_rate_wpm",
    "time_timing_event_rate_per_min",
    "time_timing_event_entropy",
    "time_timing_acceleration_per_min2",
)

PHONATION_KEYS = (
    "voice_f0_mean_hz",
    "voice_f0_median_hz",
    "voice_f0_sd_hz",
    "voice_f0_cv",
    "voice_f0_iqr_hz",
    "voice_f0_range_5_95_hz",
    "voice_f0_slope_hz_per_s",
    "voice_f0_abs_change_hz",
    "voice_voiced_ratio",
    "voice_intensity_mean_dbfs",
    "voice_intensity_median_dbfs",
    "voice_intensity_sd_db",
    "voice_intensity_iqr_db",
    "voice_intensity_slope_db_per_s",
    "voice_jitter_local",
    "voice_shimmer_local",
    "voice_hnr_mean_db",
    "voice_hnr_median_db",
    "voice_hnr_sd_db",
    "voice_hnr_iqr_db",
    "voice_cpp_mean_db",
    "voice_cpp_median_db",
    "voice_cpp_sd_db",
    "voice_cpp_iqr_db",
    "voice_break_count",
    "voice_break_rate_per_min",
    "voice_break_proportion",
    "voice_f0_range_semitones",
    "voice_f0_mad_semitones",
    "voice_intensity_range_db",
    "voice_intensity_cv",
    "voice_nhr_mean_db",
)

RESONANCE_KEYS = (
    "spectral_f1_mean_hz",
    "spectral_f1_sd_hz",
    "spectral_f2_mean_hz",
    "spectral_f2_sd_hz",
    "spectral_f3_mean_hz",
    "spectral_f3_sd_hz",
    "spectral_b1_mean_hz",
    "spectral_b1_sd_hz",
    "spectral_b2_mean_hz",
    "spectral_b2_sd_hz",
    "spectral_b3_mean_hz",
    "spectral_b3_sd_hz",
)

SPECTRUM_KEYS = (
    "spectral_centroid_mean_hz",
    "spectral_centroid_sd_hz",
    "spectral_spread_mean_hz",
    "spectral_spread_sd_hz",
    "spectral_slope_mean_db_per_hz",
    "spectral_slope_sd_db_per_hz",
    "spectral_rolloff_85_mean_hz",
    "spectral_rolloff_85_sd_hz",
    "spectral_flux_mean",
    "spectral_flux_sd",
    "spectral_flatness_mean",
    "spectral_flatness_sd",
    "spectral_entropy_mean",
    "spectral_entropy_sd",
    "spectral_energy_mean_db",
    "spectral_energy_sd_db",
    "spectral_skewness_mean",
    "spectral_skewness_sd",
    "spectral_kurtosis_mean",
    "spectral_kurtosis_sd",
    "spectral_low_high_energy_ratio_db",
    *(
        f"spectral_mfcc_{coefficient}_{stat}"
        for coefficient in range(1, 14)
        for stat in ("mean", "sd", "skewness", "kurtosis")
    ),
)

RHYTHM_KEYS = (
    "time_syllable_duration_mean_s",
    "time_syllable_duration_sd_s",
    "time_syllable_duration_cv",
    "time_syllable_duration_npvi",
)

ALL_KEYS = (
    QUALITY_KEYS + TIMING_KEYS + PHONATION_KEYS + RESONANCE_KEYS + SPECTRUM_KEYS + RHYTHM_KEYS
)

_DEFINITIONS = (
    FeatureDefinition(
        key="audio_duration_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="audio_dc_offset",
        pack="acoustic",
        level="recording",
        unit="amplitude",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="audio_clipping_ratio",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="audio_rms_dbfs",
        pack="acoustic",
        level="recording",
        unit="dBFS",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_speech_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_speech_ratio",
        pack="acoustic",
        level="recording",
        unit="ratio",
        prerequisites=("time_speech_s",),
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_voiced_segment_mean_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_voiced_segment_sd_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_pause_count",
        pack="acoustic",
        level="recording",
        unit="count",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_pause_rate_per_min",
        pack="acoustic",
        level="recording",
        unit="count/min",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_pause_mean_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_pause_sd_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_pause_max_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_long_pause_count",
        pack="acoustic",
        level="recording",
        unit="count",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_response_latency_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_overlap_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_words_per_min",
        pack="acoustic",
        level="recording",
        unit="words/min",
        prerequisites=("time_speech_s",),
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_syllables_per_min",
        pack="acoustic",
        level="recording",
        unit="syllables/min",
        prerequisites=("time_speech_s",),
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_articulation_rate_syllables_per_s",
        pack="acoustic",
        level="recording",
        unit="syllables/s",
        prerequisites=("time_speech_s",),
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_median_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_cv",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_iqr_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_range_5_95_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_slope_hz_per_s",
        pack="acoustic",
        level="recording",
        unit="Hz/s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_f0_abs_change_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_voiced_ratio",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_intensity_mean_dbfs",
        pack="acoustic",
        level="recording",
        unit="dBFS",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_intensity_median_dbfs",
        pack="acoustic",
        level="recording",
        unit="dBFS",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_intensity_sd_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_intensity_iqr_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_intensity_slope_db_per_s",
        pack="acoustic",
        level="recording",
        unit="dB/s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_jitter_local",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_shimmer_local",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_hnr_mean_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_hnr_median_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_hnr_sd_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_hnr_iqr_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_cpp_mean_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_cpp_median_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_cpp_sd_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="voice_cpp_iqr_db",
        pack="acoustic",
        level="recording",
        unit="dB",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f1_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f1_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f2_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f2_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f3_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_f3_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b1_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b1_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b2_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b2_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b3_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_b3_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_centroid_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_centroid_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_spread_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_spread_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_slope_mean_db_per_hz",
        pack="acoustic",
        level="recording",
        unit="dB/Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_slope_sd_db_per_hz",
        pack="acoustic",
        level="recording",
        unit="dB/Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_rolloff_85_mean_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_rolloff_85_sd_hz",
        pack="acoustic",
        level="recording",
        unit="Hz",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_flux_mean",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_flux_sd",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_flatness_mean",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_flatness_sd",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_entropy_mean",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="spectral_entropy_sd",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_syllable_duration_mean_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_syllable_duration_sd_s",
        pack="acoustic",
        level="recording",
        unit="s",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_syllable_duration_cv",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
    FeatureDefinition(
        key="time_syllable_duration_npvi",
        pack="acoustic",
        level="recording",
        unit="ratio",
        population="adult",
        reference="SAY catalog v1",
    ),
)

# Conservative domain unions from docs/research/neurodegenerative-speech-feature-sources.md:
# timing sources 1--6 and 8; prosody sources 1--4 and 6--9; phonation sources
# 1--3 and 5--9; spectral sources 2, 5, and 8. Standard MFCC/spectral
# descriptors inherit only the source-supported spectral union.
_TIMING_DISORDERS = (
    "ad",
    "als",
    "ataxia",
    "cbs",
    "dlb",
    "ftd",
    "hd",
    "mci",
    "mnd",
    "ms",
    "msa",
    "pd",
    "pdd",
    "ppa",
    "psp",
)
_PROSODY_DISORDERS = (
    "ad",
    "als",
    "cbs",
    "dlb",
    "ftd",
    "hd",
    "mci",
    "mnd",
    "ms",
    "msa",
    "pd",
    "pdd",
    "ppa",
    "psp",
)
_PHONATION_DISORDERS = _TIMING_DISORDERS
_SPECTRAL_DISORDERS = ("ad", "als", "ataxia", "hd", "mci", "ms", "msa", "pd", "psp")

_TIMING_COMPANION_UNITS = {
    "time_pause_total_s": "s",
    "time_pause_median_s": "s",
    "time_pause_iqr_s": "s",
    "time_pause_cv": "ratio",
    "time_pause_proportion": "ratio",
    "time_speech_segment_count": "count",
    "time_speech_segment_rate_per_min": "count/min",
    "time_speech_segment_median_s": "s",
    "time_speech_segment_iqr_s": "s",
    "time_speech_segment_cv": "ratio",
    "time_speech_segment_max_s": "s",
    "time_between_utterance_pause_proportion": "ratio",
    "time_max_local_speech_rate_wpm": "words/min",
    "time_timing_event_rate_per_min": "events/min",
    "time_timing_event_entropy": "ratio",
    "time_timing_acceleration_per_min2": "events/min2",
}

_VOICE_COMPANION_METADATA = {
    "voice_break_count": ("count", "phonation", "language_independent"),
    "voice_break_rate_per_min": ("count/min", "phonation", "language_independent"),
    "voice_break_proportion": ("ratio", "phonation", "language_independent"),
    "voice_f0_range_semitones": ("semitones", "prosody", "language_sensitive"),
    "voice_f0_mad_semitones": ("semitones", "prosody", "language_sensitive"),
    "voice_intensity_range_db": ("dB", "prosody", "language_sensitive"),
    "voice_intensity_cv": ("ratio", "prosody", "language_sensitive"),
    "voice_nhr_mean_db": ("dB", "phonation", "language_independent"),
}

_ADVANCED_SPECTRAL_UNITS = {
    "spectral_energy_mean_db": "dB",
    "spectral_energy_sd_db": "dB",
    "spectral_skewness_mean": "ratio",
    "spectral_skewness_sd": "ratio",
    "spectral_kurtosis_mean": "ratio",
    "spectral_kurtosis_sd": "ratio",
    "spectral_low_high_energy_ratio_db": "dB",
}

_DEFINITIONS += tuple(
    FeatureDefinition(
        key=key,
        pack="acoustic",
        level="recording",
        unit=unit,
        population="adult",
        reference="Neurodegenerative speech feature expansion v1",
        domain="timing",
        language_scope="language_independent",
        tasks=("connected_speech",),
        disorders=_TIMING_DISORDERS,
        evidence_level="derived_companion",
    )
    for key, unit in _TIMING_COMPANION_UNITS.items()
)

_DEFINITIONS += tuple(
    FeatureDefinition(
        key=key,
        pack="acoustic",
        level="recording",
        unit=unit,
        population="adult",
        reference="Neurodegenerative speech feature expansion v1",
        domain=domain,
        language_scope=language_scope,
        tasks=("connected_speech", "sustained_vowel"),
        disorders=_PROSODY_DISORDERS if domain == "prosody" else _PHONATION_DISORDERS,
        evidence_level="derived_companion",
    )
    for key, (unit, domain, language_scope) in _VOICE_COMPANION_METADATA.items()
)

_DEFINITIONS += tuple(
    FeatureDefinition(
        key=key,
        pack="acoustic",
        level="recording",
        unit=unit,
        population="adult",
        reference="Neurodegenerative speech feature expansion v1",
        domain="spectral",
        language_scope="language_sensitive",
        tasks=("connected_speech", "sustained_vowel"),
        disorders=_SPECTRAL_DISORDERS,
        evidence_level="standard_feature_set",
    )
    for key, unit in (
        *_ADVANCED_SPECTRAL_UNITS.items(),
        *((key, "coefficient") for key in SPECTRUM_KEYS if key.startswith("spectral_mfcc_")),
    )
)

_registered = False


def register_acoustic_features() -> None:
    """Register the acoustic pack definitions (idempotent)."""
    global _registered
    if _registered:
        return
    for definition in _DEFINITIONS:
        register_feature(definition)
    _registered = True
